### ISSUE TITLE
Unable to Compile on *BuntU 18.04

### ISSUE THREAD

**Issue by SynchronisticSavage** [VideoMapping/lpmtX2#19]
tried with multiple versions of OpenFrameworks including 0.9.4, 0.9.5, 0.9.8 0.10 and from git.
think the first error i ran into was:

/home/open/src/of/openFrameworks/apps/VJ/lpmtX2/src/kinectManager.cpp:43:85: error: no matching function for call to ‘ofxCvGrayscaleImage::setFromPixels(ofPixels&, const int&, const int&)’
  grayImage.setFromPixels(kinect.getDepthPixels(), kinect.width, kinect.height);
...
...
note:   candidate expects 1 argument, 3 provided

was able to fudge it to get past this error by removing the additional arguments to the ofxCVGrayscaleImage call(perhaps breaking something?)

and then ran into this error:

collect2: error: ld returned 1 exit status
../../../libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:382: recipe for target 'bin/lpmtX2' failed
and/or perhaps others on other versions...
would really like to get lpmt going on the latest xubuntu
any help would be appreciated, and perhaps even rewarded... ;)
